#==========================================================
#= PriceArt Web Service - Versione Sicurezza JWT
#==========================================================
server:
  port: 5071
 
spring:
  profiles:
    active: list1
  application:
    name: PriceArtService
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: 123_Adiener
    url: jdbc:postgresql://localhost:5433/shop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
# ==============================================================    
#= Opzioni Accesso Servizio gestuser            
# ==============================================================
gestuser:
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser
  password: BimBumBam_2018
